m_escape Module Reference
NAME
M_escape(3f) - [M_escape] substitute escape sequences for XML-like syntax in strings
Functions/Subroutines
character(len=:) function, allocatable, public esc (string, clear_at_end)
NAME
esc(3f) - [M_escape] substitute escape sequences for XML-like syntax in strings
character(len=:) function, allocatable, public color (string, fg, bg, style)
NAME
color(3f) - [M_escape] colorize text using a simple function-based approach (LICENSE:PD)
SYNOPSIS
subroutine, public color_mode (switch)
NAME
color_mode(3f) - [M_escape] toggle style effects of color(3f) on and off (LICENSE:PD)
SYNOPSIS
subroutine vt102 ()
subroutine, public esc_mode (manner)
NAME
esc_mode(3f) - [M_escape] select processing mode for output from esc(3f)
SYNOPSIS
subroutine wipe_dictionary ()
subroutine, public update (key, valin)
NAME
update(3f) - [M_escape] update internal dictionary given keyword and value (LICENSE:PD)
SYNOPSIS
character(len=:) function, allocatable get (key)
subroutine, public print_dictionary (header)
NAME
print_dictionary(3f) - [ARGUMENTS:M_CLI2] print internal dictionary created by calls to update(3f) (LICENSE:PD)
SYNOPSIS
subroutine split (input_line, array, delimiters)
character(len=:) function, allocatable, public attr (attribute, text)
NAME
attr(3f) - [M_escape] colorize text using a simple function-based approach (LICENSE:PD)
SYNOPSIS
Variables
logical, save g_color =.true.
logical, save debug =.false.
character(len=:), dimension(:), allocatable, save keywords
character(len=:), dimension(:), allocatable, save values
integer, dimension(:), allocatable, save counts
character(len=:), allocatable, save mode
character(len= *), parameter nl =new_line('a')
character(len= *), parameter escape =achar(27) \`
character(len= *), parameter code_start =ESCAPE//'['
character(len= *), parameter code_end ='m'
character(len= *), parameter code_reset =CODE_START//'0'//CODE_END
character(len= *), parameter clear_display =CODE_START//'2J'
character(len= *), parameter home_display =CODE_START//'H'
character(len= *), parameter bell =achar(7)
character(len= *), parameter bold_on ='1'
character(len= *), parameter italic_on ='3'
character(len= *), parameter underline_on ='4'
character(len= *), parameter inverse_on ='7'
character(len= *), parameter bold_off ='22'
character(len= *), parameter italic_off ='23'
character(len= *), parameter underline_off ='24'
character(len= *), parameter inverse_off ='27'
character(len= *), parameter color_fg_black ='30'
character(len= *), parameter color_fg_red ='31'
character(len= *), parameter color_fg_green ='32'
character(len= *), parameter color_fg_yellow ='33'
character(len= *), parameter color_fg_blue ='34'
character(len= *), parameter color_fg_magenta ='35'
character(len= *), parameter color_fg_cyan ='36'
character(len= *), parameter color_fg_white ='37'
character(len= *), parameter color_fg_default ='39'
character(len= *), parameter color_fg_black_intense ='90'
character(len= *), parameter color_fg_red_intense ='91'
character(len= *), parameter color_fg_green_intense ='92'
character(len= *), parameter color_fg_yellow_intense ='93'
character(len= *), parameter color_fg_blue_intense ='94'
character(len= *), parameter color_fg_magenta_intense ='95'
character(len= *), parameter color_fg_cyan_intense ='96'
character(len= *), parameter color_fg_white_intense ='97'
character(len= *), parameter color_bg_black ='40'
character(len= *), parameter color_bg_red ='41'
character(len= *), parameter color_bg_green ='42'
character(len= *), parameter color_bg_yellow ='43'
character(len= *), parameter color_bg_blue ='44'
character(len= *), parameter color_bg_magenta ='45'
character(len= *), parameter color_bg_cyan ='46'
character(len= *), parameter color_bg_white ='47'
character(len= *), parameter color_bg_default ='49'
character(len= *), parameter color_bg_black_intense ='100'
character(len= *), parameter color_bg_red_intense ='101'
character(len= *), parameter color_bg_green_intense ='102'
character(len= *), parameter color_bg_yellow_intense ='103'
character(len= *), parameter color_bg_blue_intense ='104'
character(len= *), parameter color_bg_magenta_intense ='105'
character(len= *), parameter color_bg_cyan_intense ='106'
character(len= *), parameter color_bg_white_intense ='107'
character(len= *), parameter, public fg_red = CODE_START//COLOR_FG_RED//CODE_END
character(len= *), parameter, public fg_cyan = CODE_START//COLOR_FG_CYAN//CODE_END
character(len= *), parameter, public fg_magenta = CODE_START//COLOR_FG_MAGENTA//CODE_END
character(len= *), parameter, public fg_blue = CODE_START//COLOR_FG_BLUE//CODE_END
character(len= *), parameter, public fg_green = CODE_START//COLOR_FG_GREEN//CODE_END
character(len= *), parameter, public fg_yellow = CODE_START//COLOR_FG_YELLOW//CODE_END
character(len= *), parameter, public fg_white = CODE_START//COLOR_FG_WHITE//CODE_END
character(len= *), parameter, public fg_ebony = CODE_START//COLOR_FG_BLACK//CODE_END
character(len= *), parameter, public fg_black = CODE_START//COLOR_FG_BLACK//CODE_END
character(len= *), parameter, public fg_default = CODE_START//COLOR_FG_DEFAULT//CODE_END
character(len= *), parameter, public bg_red = CODE_START//COLOR_BG_RED//CODE_END
character(len= *), parameter, public bg_cyan = CODE_START//COLOR_BG_CYAN//CODE_END
character(len= *), parameter, public bg_magenta = CODE_START//COLOR_BG_MAGENTA//CODE_END
character(len= *), parameter, public bg_blue = CODE_START//COLOR_BG_BLUE//CODE_END
character(len= *), parameter, public bg_green = CODE_START//COLOR_BG_GREEN//CODE_END
character(len= *), parameter, public bg_yellow = CODE_START//COLOR_BG_YELLOW//CODE_END
character(len= *), parameter, public bg_white = CODE_START//COLOR_BG_WHITE//CODE_END
character(len= *), parameter, public bg_ebony = CODE_START//COLOR_BG_BLACK//CODE_END
character(len= *), parameter, public bg_black = CODE_START//COLOR_BG_BLACK//CODE_END
character(len= *), parameter, public bg_default = CODE_START//COLOR_BG_DEFAULT//CODE_END
character(len= *), parameter, public bold = CODE_START//BOLD_ON//CODE_END
character(len= *), parameter, public italic = CODE_START//ITALIC_ON//CODE_END
character(len= *), parameter, public inverse = CODE_START//INVERSE_ON//CODE_END
character(len= *), parameter, public underline = CODE_START//UNDERLINE_ON//CODE_END
character(len= *), parameter, public unbold = CODE_START//BOLD_OFF//CODE_END
character(len= *), parameter, public unitalic = CODE_START//ITALIC_OFF//CODE_END
character(len= *), parameter, public uninverse = CODE_START//INVERSE_OFF//CODE_END
character(len= *), parameter, public ununderline = CODE_START//UNDERLINE_OFF//CODE_END
character(len= *), parameter, public reset = CODE_RESET
character(len= *), parameter, public clear = HOME_DISPLAY//CLEAR_DISPLAY
Detailed Description
NAME
M_escape(3f) - [M_escape] substitute escape sequences for XML-like syntax in strings
SYNOPSIS
 use M_escape, only : esc, esc_mode, update
 use M_escape, only : attr
 use M_escape, only : color, color_mode
DESCRIPTION
M_escape is a Fortran module for using XML-like syntax to add attributes to terminal output such as color.
ANSI escape sequences are not universally supported by all terminal emulators; and normally should be suppressed when not going to a tty device. This routine provides the basic structure to support such behaviors. or to perhaps in the future generate a CSS style sheet and HTML instead of text to the terminal, ...
Alternatively, direct use of the escape sequences is supported, as well as a functional interface, and an object-oriented approach.
The original concept was to allow formatting by using an existing XML library to allow the user to write HTML and to format it on a terminal like w3m, lynx, and link do. And in some ways this is an opposite approach in that it is directly formatting the text by using a similar syntax to directly generate text attributes; but it is a much simpler approach programmatically.
Typically, you should use M_system::system_istty(3f) to set the default to `plain` instead of `color` when the output file is not a terminal.
MAJOR FEATURES
o Add ANSI terminal escape sequences with an XML-like syntax with ESC(3f). o suppress the escape sequence output with ESC_MODE(3f). o add, delete, and replace what strings are produced using UPDATE(3f).
LIMITATIONS
o colors are not nestable, keywords are case-sensitive, o not all terminals obey the sequences. On Windows, it is best if you use Windows 10+ and/or the Linux mode; although it has worked with all CygWin and MinGW and Putty windows and mintty.
FUTURE
Full support for alternate output formats like HTML and popular markdown syntax. For example
ANSI HTML Markdown
#
## ** and ** __ and __
Apparently have to make a stack of colors to allow nesting colors
How common are extensions like xterm-256 has to set RGB values for colors and so on?
Should a call to system_istty(3f) be built in to turn off escape sequences when a terminal is not present?
For color or pre-defined words a case statement could be used to call specific functions to support platforms like old Microsoft consoles that require a function call to assign text attributes instead of in-band ANSI escape control sequences. See the `Rosetta Code` web site for examples of generating color in Microsoft consoles.
Attributes are currently ended at the end of each call to esc(3f). Perhaps allow multi-line formatting?
Ultimately, an object-oriented package with capabilities like ncurses to define a `pad` and move and resize and format it would be ideal and very useful. Also see fixedform(3f) in the GPF (General Fortran Package).
It is a shame xterm(1) does not support pixel-oriented abilities to define a `graphics` area or support canvas(3c)-like in-band graphics, somewhat like Tektronix terminals.
overload + to replace //
EXAMPLE
Sample program
program demo_M_escape use M_escape, only : esc, esc_mode implicit none character(len=1024) :: line real :: value write(*,'(a)') esc('<r><W>ERROR:</W>This should appear as red text</y>') write(*,'(a)') esc('<y>WARNING:</y> This should appear as default text')
value=3.4567 if((value>0.0) .and. (value<100.0))then write(line,fmt='(`<w><G>GREAT</G></w>:The new value <Y><b>`,f8.4,`</b></Y> is in range`)')value else write(line,fmt='(`<R><e>ERROR</e></R>:The new value <Y><b>`,g0,`</b></Y> is out of range`)')value endif
write(*,'(a)')esc(trim(line)) ! write as plain text call esc_mode(manner='plain') write(*,'(a)')esc(trim(line))
end program demo_M_escape
ALTERNATE DIRECT USE
Alternatively, you may use the escape sequences directly
program direct use M_escape, only : & ! FOREGROUND COLORS & fg_red, fg_cyan, fg_magenta, fg_blue, & & fg_green, fg_yellow, fg_white, fg_ebony, & & fg_default, & ! BACKGROUND COLORS & bg_red, bg_cyan, bg_magenta, bg_blue, & & bg_green, bg_yellow, bg_white, bg_ebony, & & bg_default, & ! ATTRIBUTES & bold, italic, inverse, underline, & & unbold, unitalic, uninverse, ununderline, & & reset, & ! DISPLAY & clear implicit none write(*,'(*(g0))')fg_red,bg_green,bold,'Hello!',reset end program direct
ALTERNATE FUNCTIONAL INTERFACE
If you prefer a functional interface, use the attr(3f) function with the same keywords as with the esc(3f) function. Note that esc_mode(3f) will work with this function.
program functional use M_escape, only : attr, esc_mode implicit none call printme('color') call printme('plain') call printme('raw') contains subroutine printme(mymode) character(len=*),intent(in) :: mymode call esc_mode(mymode) write(*,'(a)')mymode write(*,'(*(g0))',advance='no') & & attr('red:BLUE:bold','Hello!'), & & 'and everything is back to defaults or ', & & attr('RED:blue:bold'),'Hello Again!', & & attr('/BLUE'),' Well, the text color is still on.',attr('reset') write(*,'(*(g0))',advance='yes')' Back to normal writes.' end subroutine printme end program functional
ALTERNATE OBJECT ORIENTED
Function/Subroutine Documentation
attr()
character(len=:) function, allocatable, public m_escape::attr (character(len=*), intent(in) attribute, character(len=*), intent(in), optional text)
NAME
attr(3f) - [M_escape] colorize text using a simple function-based approach (LICENSE:PD)
SYNOPSIS
function attr(attribute) result (out)
character(len=*),intent(in) :: attribute character(len=:),allocatable :: out
DESCRIPTION
attr(3f) uses the same keywords as esc(3f) to send ANSI escape sequences to the display screen, except instead of using a pseudo-XML string to select the codes it uses a simple colon-delimited list of the keywords.
OPTIONS
attribute colon, space, or comma-delimited list of attribute keywords as defined in the esc(3f) procedure. text if supplied it is printed and then an attribute reset is added
RETURNS
out the output is the strings (by default ANSI video display escape sequences, see update(3f)) assigned by the keywords.
EXAMPLE
Sample program
program demo_attr use M_escape, only : attr, esc_mode implicit none call printme('color') call printme('plain') call printme('raw') contains subroutine printme(mymode) character(len=*),intent(in) :: mymode call esc_mode(mymode) write(*,'(a)')mymode write(*,'(*(g0))',advance='no')attr('red:BLUE:bold','Hello!'), & & 'and everything is back to defaults or ', & & attr('RED:blue:bold'),'Hello Again!', & & attr('/RED'),' Well, the text color is still blue.',attr('reset') write(*,'(*(g0))',advance='yes')' Back to a normal write statement.' end subroutine printme end program demo_attr
AUTHOR
John S. Urban, 2020
LICENSE
Public Domain
References esc(), get(), mode, split(), and vt102().
color()
character(len=:) function, allocatable, public m_escape::color (character(len=*), intent(in) string, character(len=*), intent(in), optional fg, character(len=*), intent(in), optional bg, character(len=*), intent(in), optional style)
NAME
color(3f) - [M_escape] colorize text using a simple function-based approach (LICENSE:PD)
SYNOPSIS
use M_escape, only : color, color_mode, &
! FOREGROUND COLORS & fg_red, fg_cyan, fg_magenta, fg_blue, & & fg_green, fg_yellow, fg_white, fg_ebony, & & fg_default, & ! BACKGROUND COLORS & bg_red, bg_cyan, bg_magenta, bg_blue, & & bg_green, bg_yellow, bg_white, bg_ebony, & & bg_default, & ! ATTRIBUTES & bold, italic, inverse, underline, & & unbold, unitalic, uninverse, ununderline, & & reset, & ! DISPLAY & clear
function color(string,fg,bg,style) result (out)
character(len=*),intent(in) :: string character(len=*),intent(in),optional :: fg character(len=*),intent(in),optional :: bg character(len=*),intent(in),optional :: style
DESCRIPTION
The color constant strings can be used directly but unconditionally in an output statement. To allow the attributes to be ignored they can be called with the color(3f) routine, which the color_mode(3f) procedure can be used to toggle on and off. Note that this routine does an implicit reset at the end of each use.
OPTIONS
string string to assign attributes to fg foreground color constant bg background color constant style style keyword or concatenated style keywords
EXAMPLE
Sample program
program demo_color use M_escape, only : color, color_mode, & ! FOREGROUND COLORS & fg_red, fg_cyan, fg_magenta, fg_blue, & & fg_green, fg_yellow, fg_white, fg_ebony, & & fg_default, & ! BACKGROUND COLORS & bg_red, bg_cyan, bg_magenta, bg_blue, & & bg_green, bg_yellow, bg_white, bg_ebony, & & bg_default, & ! ATTRIBUTES & bold, italic, inverse, underline, & & unbold, unitalic, uninverse, ununderline, & & reset, & ! DISPLAY & clear implicit none write(*,'(*(g0))')fg_red,bg_green,bold,' Hello! ',reset
write(*,'(a)')color(' Hello! ',fg=fg_white,bg=bg_red,style=italic//bold) call color_mode(.false.) write(*,'(a)')color(' Hello! ',fg=fg_red,bg=bg_red,style=italic//bold) end program demo_color
AUTHOR
John S. Urban, 2020
LICENSE
Public Domain
References g_color, and reset.
color_mode()
subroutine, public m_escape::color_mode (logical, intent(in) switch)
NAME
color_mode(3f) - [M_escape] toggle style effects of color(3f) on and off (LICENSE:PD)
SYNOPSIS
subroutine color_mode(switch)
logical,intent(in) :: switch
DESCRIPTION
The color constant strings can be used directly but unconditionally in an output statement. To allow the attributes to be ignored they can be called with the color(3f) routine, which the color_mode(3f) procedure can be used to toggle on and off. Note that this routine does an implicit reset at the end of each use.
OPTIONS
switch turn attributes set by color(3f) on and off
EXAMPLE
Sample program
program demo_color_mode use M_escape, only : color, color_mode, & ! FOREGROUND COLORS & fg_red, fg_cyan, fg_magenta, fg_blue, & & fg_green, fg_yellow, fg_white, fg_ebony, & & fg_default, & ! BACKGROUND COLORS & bg_red, bg_cyan, bg_magenta, bg_blue, & & bg_green, bg_yellow, bg_white, bg_ebony, & & bg_default, & ! ATTRIBUTES & bold, italic, inverse, underline, & & unbold, unitalic, uninverse, ununderline, & & reset, & ! DISPLAY & clear implicit none write(*,'(*(g0))')fg_red,bg_green,bold,' Hello! ',reset
write(*,'(a)')color(' Hello! ',fg=fg_white,bg=bg_red,style=italic//bold) call color_mode(.false.) write(*,'(a)')color(' Hello! ',fg=fg_red,bg=bg_red,style=italic//bold) end program demo_color_mode
AUTHOR
John S. Urban, 2020
LICENSE
Public Domain
References g_color.
esc()
character(len=:) function, allocatable, public m_escape::esc (character(len=*), intent(in) string, logical, intent(in), optional clear_at_end)
NAME
esc(3f) - [M_escape] substitute escape sequences for XML-like syntax in strings
SYNOPSIS
 function esc(string,clear_at_end) result (expanded)

   character(len=*),intent(in) :: string
   logical,intent(in),optional :: clear_at_end
   character(len=:),allocatable :: expanded
DESCRIPTION
Use XML-like syntax to add attributes to terminal output such as color.
ANSI escape sequences are not universally supported by all terminal emulators; and normally should be suppressed when not going to a tty device. This routine provides the basic structure to support such behaviors.
OPTIONS
string input string of form
            "<attribute_name>string</attribute_name> ...".

           where the current attributes are color names,
           bold, italic, underline, ...
clear_at_end By default, a sequence to clear all text attributes is sent at the end of the returned text if an escape character appears in the output string. This can be turned off by setting this value to false.
KEYWORDS
current keywords
colors: r, red, R, RED g, green, G, GREEN b, blue, B, BLUE m, magenta, M, MAGENTA c, cyan, C, CYAN y, yellow, Y, YELLOW e, ebony, E, EBONY w, white, W, WHITE attributes: it, italic bo, bold un, underline other: clear esc, escape default gt lt
By default, if the color mnemonics (ie. the keywords) are uppercase they change the background color. If lowercase, the foreground color.
The `default` keyword is typically used explicitly when clear_at_end=.false.
Add, delete, and replace what strings are produced using UPDATE(3f).
LIMITATIONS
o colors are not nestable, keywords are case-sensitive, o not all terminals obey the sequences. On Windows, it is best if you use Windows 10+ and/or the Linux mode; although it has worked with all CygWin and MinGW and Putty windows and mintty. o you should use `<gt>` and `<lt>` instead of `>` and `<` in a string processed by esc(3f) instead of in any plain text output so that the raw mode will create correct input for the esc(3f) function if read back in.
EXAMPLE
Sample program
program demo_esc use M_escape, only : esc, esc_mode, update write(*,'(a)') esc('<clear>TEST DEFAULTS:') call printstuff()
write(*,'(a)') esc('TEST MANNER=PLAIN:') call esc_mode(manner='plain') call printstuff()
write(*,'(a)') esc('TEST MANNER=RAW:') call esc_mode(manner='raw') call printstuff()
write(*,'(a)') esc('TEST MANNER=color:') call esc_mode(manner='color') call printstuff()
write(*,'(a)') esc('TEST ADDING A CUSTOM SEQUENCE:') call update('blink',char(27)//'[5m') call update('/blink',char(27)//'[38m') write(*,'(a)') esc('<blink>Items for Friday</blink>')
contains subroutine printstuff()
write(*,'(a)') esc('<r>RED</r>,<g>GREEN</g>,BLUE') write(*,'(a)') esc('CYAN,<m>MAGENTA</g>,<y>YELLOW</y>') write(*,'(a)') esc('<w>WHITE</w> and <e>EBONY</e>')
write(*,'(a)') esc('Adding <bo>bold</bo>') write(*,'(a)') esc('<bo><r>RED</r>,<g>GREEN</g>,BLUE</bo>') write(*,'(a)') esc('<bo>CYAN,<m>MAGENTA</g>,<y>YELLOW</y></bo>') write(*,'(a)') esc('<bo><w>WHITE</w> and <e>EBONY</e></bo>')
write(*,'(a)') esc('Adding
') write(*,'(a)') esc('<bo>
<r>RED</r>,<g>GREEN</g>,BLUE</bo>') write(*,'(a)') esc('<bo>
CYAN,<m>MAGENTA</g>,<y>YELLOW</y></bo>') write(*,'(a)') esc('<bo>
<w>WHITE</w> and <e>EBONY</e></bo>')
write(*,'(a)') esc('Adding
') write(*,'(a)') esc('<bo>
<it><r>RED</r>,<g>GREEN</g>,BLUE</it></bo>') write(*,'(a)') esc('<bo>
<it>CYAN,<m>MAGENTA</g>,<y>YELLOW</it></y></bo>') write(*,'(a)') esc('<bo>
<it><w>WHITE</w> and <e>EBONY</e></bo>')
write(*,'(a)') esc('Adding <in>inverse</in>') write(*,'(a)') esc('<in><bo>
<it><r>RED</r>,<g>GREEN</g>,BLUE</it></bo></in>') write(*,'(a)') esc('<in><bo>
<it>CYAN,<m>MAGENTA</g>,<y>YELLOW</it></y></bo></in>') write(*,'(a)') esc('<in><bo>
<it><w>WHITE</w> and <e>EBONY</e></bo></in>') end subroutine printstuff
end program demo_esc
References code_reset, debug, escape, get(), keywords, mode, and vt102().
esc_mode()
subroutine, public m_escape::esc_mode (character(len=*), intent(in) manner)
NAME
esc_mode(3f) - [M_escape] select processing mode for output from esc(3f)
SYNOPSIS
subroutine esc_mode(manner)
character(len=*),intent(in) :: manner
DESCRIPTION
Turn off the generation of strings associated with the XML keywords in the string generated by the esc(3f) function, or display the text in raw mode as it was passed to esc(3f) or return to ANSI escape control sequence generation.
OPTIONS
MANNER The current manners or modes supported via the ESC_MODE(3f) procedure are
plain suppress the output associated with keywords color(default) commonly supported escape sequences raw echo the input to ESC(3f) as its output reload restore original keyword meanings deleted or replaced by calls to update(3f).
EXAMPLE
Sample program
program demo_esc_mode use M_escape, only : esc, esc_mode implicit none character(len=1024) :: line real :: value
value=3.4567 if((value>0.0) .and. (value<100.0))then write(line,fmt='(`&
       &<w><G>GREAT</G></w>: The value <Y><b>`,f8.4,`</b></Y> is in range &
       &`)')value else write(line,fmt='(`&
       &<R><e>ERROR</e></R>:The new value <Y><b>`,g0,`</b></Y> is out of range&
       & `)')value endif
write(*,'(a)')esc(trim(line))
call esc_mode(manner='plain') ! write as plain text write(*,'(a)')esc(trim(line)) call esc_mode(manner='raw') ! write as-is write(*,'(a)')esc(trim(line)) call esc_mode(manner='ansi') ! return to default mode write(*,'(a)')esc(trim(line))
end program demo_esc_mode
References mode, and vt102().
get()
character(len=:) function, allocatable m_escape::get (character(len=*), intent(in) key) [private]
References counts, keywords, and values.
print_dictionary()
subroutine, public m_escape::print_dictionary (character(len=*), intent(in), optional header)
NAME
print_dictionary(3f) - [ARGUMENTS:M_CLI2] print internal dictionary created by calls to update(3f) (LICENSE:PD)
SYNOPSIS
subroutine print_dictionary(header)
character(len=*),intent(in),optional :: header
DESCRIPTION
Print the internal dictionary created by calls to update(3f). This routine is intended to print the state of the argument list if an error occurs in using the update(3f) procedure.
OPTIONS
HEADER label to print before printing the state of the command argument list.
EXAMPLE
Typical usage:
program demo_print_dictionary use M_escape, only : esc, update, print_dictionary implicit none write(*,'(a)') esc('<clear>TEST CUSTOMIZED:') ! add custom keywords call update('blink',char(27)//'[5m') call update('/blink',char(27)//'[38m') call print_dictionary('DICTIONARY') write(*,'(a)') esc('<blink>Items for Friday</blink>') end program demo_print_dictionary
Sample output
demo_print_dictionary |cat -v -e -t
AUTHOR
John S. Urban, 2020
LICENSE
Public Domain
References counts, keywords, and values.
split()
subroutine m_escape::split (character(len=*), intent(in) input_line, character(len=:), dimension(:), intent(out), allocatable array, character(len=*), intent(in), optional delimiters) [private]
update()
subroutine, public m_escape::update (character(len=*), intent(in) key, character(len=*), intent(in), optional valin)
NAME
update(3f) - [M_escape] update internal dictionary given keyword and value (LICENSE:PD)
SYNOPSIS
subroutine update(key,val)
character(len=*),intent(in) :: key character(len=*),intent(in),optional :: val
DESCRIPTION
Update internal dictionary in M_escape(3fm) module.
OPTIONS
key name of keyword to add, replace, or delete from dictionary val if present add or replace value associated with keyword. If not present remove keyword entry from dictionary.
EXAMPLE
Sample program
program demo_update use M_escape, only : esc, update write(*,'(a)') esc('<clear>TEST CUSTOMIZED:') ! add custom keywords call update('blink',char(27)//'[5m') call update('/blink',char(27)//'[38m')
write(*,'(a)') esc('<blink>Items for Friday</blink>')
write(*,'(a)',advance='no') esc('<r>RED</r>,') write(*,'(a)',advance='no') esc('BLUE,') write(*,'(a)',advance='yes') esc('<g>GREEN</g>')
! delete call update('r') call update('/r') ! replace call update('b','<<<<') call update('/b','>>>>') write(*,'(a)',advance='no') esc('<r>RED</r>,') write(*,'(a)',advance='no') esc('BLUE,') write(*,'(a)',advance='yes') esc('<g>GREEN</g>')
end program demo_update
AUTHOR
John S. Urban, 2020
LICENSE
Public Domain
References counts, keywords, and values.
vt102()
subroutine m_escape::vt102 () [private]
References bell, bg_blue, bg_cyan, bg_default, bg_ebony, bg_green, bg_magenta, bg_red, bg_white, bg_yellow, bold, clear, escape, fg_blue, fg_cyan, fg_default, fg_ebony, fg_green, fg_magenta, fg_red, fg_white, fg_yellow, inverse, italic, reset, unbold, underline, uninverse, unitalic, ununderline, update(), and wipe_dictionary().
wipe_dictionary()
subroutine m_escape::wipe_dictionary () [private]
References counts, keywords, and values.
Variable Documentation
bell
character(len=*), parameter m_escape::bell =achar(7) [private]
bg_black
character(len=*), parameter, public m_escape::bg_black = CODE_START//COLOR_BG_BLACK//CODE_END
bg_blue
character(len=*), parameter, public m_escape::bg_blue = CODE_START//COLOR_BG_BLUE//CODE_END
bg_cyan
character(len=*), parameter, public m_escape::bg_cyan = CODE_START//COLOR_BG_CYAN//CODE_END
bg_default
character(len=*), parameter, public m_escape::bg_default = CODE_START//COLOR_BG_DEFAULT//CODE_END
bg_ebony
character(len=*), parameter, public m_escape::bg_ebony = CODE_START//COLOR_BG_BLACK//CODE_END
bg_green
character(len=*), parameter, public m_escape::bg_green = CODE_START//COLOR_BG_GREEN//CODE_END
bg_magenta
character(len=*), parameter, public m_escape::bg_magenta = CODE_START//COLOR_BG_MAGENTA//CODE_END
bg_red
character(len=*), parameter, public m_escape::bg_red = CODE_START//COLOR_BG_RED//CODE_END
bg_white
character(len=*), parameter, public m_escape::bg_white = CODE_START//COLOR_BG_WHITE//CODE_END
bg_yellow
character(len=*), parameter, public m_escape::bg_yellow = CODE_START//COLOR_BG_YELLOW//CODE_END
bold
character(len=*), parameter, public m_escape::bold = CODE_START//BOLD_ON//CODE_END
bold_off
character(len=*), parameter m_escape::bold_off ='22' [private]
bold_on
character(len=*), parameter m_escape::bold_on ='1' [private]
clear
character(len=*), parameter, public m_escape::clear = HOME_DISPLAY//CLEAR_DISPLAY
clear_display
character(len=*), parameter m_escape::clear_display =CODE_START//'2J' [private]
code_end
character(len=*), parameter m_escape::code_end ='m' [private]
code_reset
character(len=*), parameter m_escape::code_reset =CODE_START//'0'//CODE_END [private]
code_start
character(len=*), parameter m_escape::code_start =ESCAPE//'[' [private]
color_bg_black
character(len=*), parameter m_escape::color_bg_black ='40' [private]
color_bg_black_intense
character(len=*), parameter m_escape::color_bg_black_intense ='100' [private]
color_bg_blue
character(len=*), parameter m_escape::color_bg_blue ='44' [private]
color_bg_blue_intense
character(len=*), parameter m_escape::color_bg_blue_intense ='104' [private]
color_bg_cyan
character(len=*), parameter m_escape::color_bg_cyan ='46' [private]
color_bg_cyan_intense
character(len=*), parameter m_escape::color_bg_cyan_intense ='106' [private]
color_bg_default
character(len=*), parameter m_escape::color_bg_default ='49' [private]
color_bg_green
character(len=*), parameter m_escape::color_bg_green ='42' [private]
color_bg_green_intense
character(len=*), parameter m_escape::color_bg_green_intense ='102' [private]
color_bg_magenta
character(len=*), parameter m_escape::color_bg_magenta ='45' [private]
color_bg_magenta_intense
character(len=*), parameter m_escape::color_bg_magenta_intense ='105' [private]
color_bg_red
character(len=*), parameter m_escape::color_bg_red ='41' [private]
color_bg_red_intense
character(len=*), parameter m_escape::color_bg_red_intense ='101' [private]
color_bg_white
character(len=*), parameter m_escape::color_bg_white ='47' [private]
color_bg_white_intense
character(len=*), parameter m_escape::color_bg_white_intense ='107' [private]
color_bg_yellow
character(len=*), parameter m_escape::color_bg_yellow ='43' [private]
color_bg_yellow_intense
character(len=*), parameter m_escape::color_bg_yellow_intense ='103' [private]
color_fg_black
character(len=*), parameter m_escape::color_fg_black ='30' [private]
color_fg_black_intense
character(len=*), parameter m_escape::color_fg_black_intense ='90' [private]
color_fg_blue
character(len=*), parameter m_escape::color_fg_blue ='34' [private]
color_fg_blue_intense
character(len=*), parameter m_escape::color_fg_blue_intense ='94' [private]
color_fg_cyan
character(len=*), parameter m_escape::color_fg_cyan ='36' [private]
color_fg_cyan_intense
character(len=*), parameter m_escape::color_fg_cyan_intense ='96' [private]
color_fg_default
character(len=*), parameter m_escape::color_fg_default ='39' [private]
color_fg_green
character(len=*), parameter m_escape::color_fg_green ='32' [private]
color_fg_green_intense
character(len=*), parameter m_escape::color_fg_green_intense ='92' [private]
color_fg_magenta
character(len=*), parameter m_escape::color_fg_magenta ='35' [private]
color_fg_magenta_intense
character(len=*), parameter m_escape::color_fg_magenta_intense ='95' [private]
color_fg_red
character(len=*), parameter m_escape::color_fg_red ='31' [private]
color_fg_red_intense
character(len=*), parameter m_escape::color_fg_red_intense ='91' [private]
color_fg_white
character(len=*), parameter m_escape::color_fg_white ='37' [private]
color_fg_white_intense
character(len=*), parameter m_escape::color_fg_white_intense ='97' [private]
color_fg_yellow
character(len=*), parameter m_escape::color_fg_yellow ='33' [private]
color_fg_yellow_intense
character(len=*), parameter m_escape::color_fg_yellow_intense ='93' [private]
counts
integer, dimension(:), allocatable, save m_escape::counts [private]
debug
logical, save m_escape::debug =.false. [private]
escape
character(len=*), parameter m_escape::escape =achar(27) \` [private]
fg_black
character(len=*), parameter, public m_escape::fg_black = CODE_START//COLOR_FG_BLACK//CODE_END
fg_blue
character(len=*), parameter, public m_escape::fg_blue = CODE_START//COLOR_FG_BLUE//CODE_END
fg_cyan
character(len=*), parameter, public m_escape::fg_cyan = CODE_START//COLOR_FG_CYAN//CODE_END
fg_default
character(len=*), parameter, public m_escape::fg_default = CODE_START//COLOR_FG_DEFAULT//CODE_END
fg_ebony
character(len=*), parameter, public m_escape::fg_ebony = CODE_START//COLOR_FG_BLACK//CODE_END
fg_green
character(len=*), parameter, public m_escape::fg_green = CODE_START//COLOR_FG_GREEN//CODE_END
fg_magenta
character(len=*), parameter, public m_escape::fg_magenta = CODE_START//COLOR_FG_MAGENTA//CODE_END
fg_red
character(len=*), parameter, public m_escape::fg_red = CODE_START//COLOR_FG_RED//CODE_END
fg_white
character(len=*), parameter, public m_escape::fg_white = CODE_START//COLOR_FG_WHITE//CODE_END
fg_yellow
character(len=*), parameter, public m_escape::fg_yellow = CODE_START//COLOR_FG_YELLOW//CODE_END
g_color
logical, save m_escape::g_color =.true. [private]
home_display
character(len=*), parameter m_escape::home_display =CODE_START//'H' [private]
inverse
character(len=*), parameter, public m_escape::inverse = CODE_START//INVERSE_ON//CODE_END
inverse_off
character(len=*), parameter m_escape::inverse_off ='27' [private]
inverse_on
character(len=*), parameter m_escape::inverse_on ='7' [private]
italic
character(len=*), parameter, public m_escape::italic = CODE_START//ITALIC_ON//CODE_END
italic_off
character(len=*), parameter m_escape::italic_off ='23' [private]
italic_on
character(len=*), parameter m_escape::italic_on ='3' [private]
keywords
character(len=:), dimension(:), allocatable, save m_escape::keywords [private]
mode
character(len=:), allocatable, save m_escape::mode [private]
nl
character(len=*), parameter m_escape::nl =new_line('a') [private]
reset
character(len=*), parameter, public m_escape::reset = CODE_RESET
unbold
character(len=*), parameter, public m_escape::unbold = CODE_START//BOLD_OFF//CODE_END
underline
character(len=*), parameter, public m_escape::underline = CODE_START//UNDERLINE_ON//CODE_END
underline_off
character(len=*), parameter m_escape::underline_off ='24' [private]
underline_on
character(len=*), parameter m_escape::underline_on ='4' [private]
uninverse
character(len=*), parameter, public m_escape::uninverse = CODE_START//INVERSE_OFF//CODE_END
unitalic
character(len=*), parameter, public m_escape::unitalic = CODE_START//ITALIC_OFF//CODE_END
ununderline
character(len=*), parameter, public m_escape::ununderline = CODE_START//UNDERLINE_OFF//CODE_END
values
character(len=:), dimension(:), allocatable, save m_escape::values [private]